__include__: [
  '../dataset/coco_indoor_4k_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]

output_dir: /home/cui/rtdetr_indoor/output/rtdetr_r50vd_coco_indoor_4k
